<a href="https://colab.research.google.com/github/shauryanegi/TensorFlow-Tutorials/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow.

More specefically, we are going to cover:

*   Introduction to Tensors
*   Getting information from tensors
*   Manipulating Tensors
*   Tensors and NumPy
*   Using @tf.function(a way to speed up your       regular Python functions)
*   Using GPU's with Tensorflow (or TPU's)
*   Exercises to try yourself!
*   List item







## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions in a tensor. (ndim = number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than one dimension)
matrix = tf.constant(([10,7],[10,7]))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [7]:
#Check the dimensions of the matrix
matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]],
                             dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [10]:
# Let us create a tensor

tensor = tf.constant([[[1, 2, 3], [2, 3, 4]], [[5, 6, 7], [10, 22,
                     12]], [[19, 14, 54], [43, 54, 53]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [10, 22, 12]],

       [[19, 14, 54],
        [43, 54, 53]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have learned so far:

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array (when n can be any number, a 0- dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Creating Tensors with tf.Variable

In [12]:
#Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [13]:
# Let's try change one of the elements in changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)

#tf.constant does not allow to change our values.

### Creating Random Tensors

Random tensors are tensors of some arbitary size which contain random numbers.

In [14]:
# Create two random (but the same) tensors
#Random initilization is important to avoid exploding/vanishing gradients and to make sure that the neural network starts well.


random_1 = tf.random.Generator.from_seed(42)  # Set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))  # Uniform distribution
random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?

(random_1, random_2, random_1 == random_2)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor (valuable for when you want to shuffle your data so inherent order does not affect learning)

not_shuffled = tf.constant([[10, 7], [3, 5], [8, 9]])
not_shuffled.ndim

# Shuffle our non-shuffled tensor

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 8,  9]], dtype=int32)>

In [16]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 8,  9],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [10,  7],
       [ 3,  5]], dtype=int32)>

Other ways to make tensors

In [18]:
#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
#Create a tensor of all zeroes
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and tensors is that tensors can be run on a GPU (much faster for numerical computation)

In [20]:
# You can also convert NumPy array into tensors

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)  # NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or vector
# y = tf.constant(vector) # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A, shape = (2,3,4)) #shape elements should be equal
B = tf.constant(numpy_A)
A , B, A.ndim, B.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3,
 1)

## Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [22]:
#Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.#ndim,  tf.size(rank_4_tensor)

SyntaxError: ignored

In [25]:
# Get various attibutes of our tensor

print ('Datatype of every element:', rank_4_tensor.dtype)
print ('Number of dimensions: ', rank_4_tensor.ndim)
print ('Shape of tensor :', rank_4_tensor.shape)
print ('Elements along the 0 axis:', rank_4_tensor.shape[0])
print ('Elements along the last axis', rank_4_tensor.shape[-1])
print ('Total number of elements in tensors:', tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor : (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis 5
Total number of elements in tensors: tf.Tensor(120, shape=(), dtype=int32)


Indexing Tensors

Tensors can be indexed just like Python lists.

In [26]:
#Get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item each of our rank 2 tensor
rank_2_tensor, rank_2_tensor[:,-1]

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [30]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor , axis = -1) #'-1' means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis = 0) #Expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_2_tensor, axis = 1) #Expand the first axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

Manipulating Tensor Operations

* Basic Operations

In [34]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10, tf.math.add(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>)

In [35]:
# Other Operations
print(tensor * 10 , tf.multiply(tensor, 10))

print(tensor / 10, tf.math.divide(tensor,10))

print(tensor - 10, tf.math.subtract(tensor, 10))

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32) tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64) tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)


# Matrix Multiplication

In Machine Learning, matrix multiplication are the most important tensor calculations.

There are two rules our tensors (or matrices) need to fulfill if we need to do matrix multiplication.

1. Inner dimensions should match
2. The resulting matrix has the shape of the outer dimension.

In [36]:
#Matrix multiplication
print(tf.matmul(tensor,tensor)), print(np.dot(tensor,tensor))

tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)
[[121  98]
 [ 42  37]]


(None, None)

In [37]:
# Matrix multiplication with Python operator "@"
# @ is used for matrix multiplication
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [38]:
tensor.shape

TensorShape([2, 2])

In [39]:
# Create a tensor of (3,2) 
X = tf.constant([[1,2,],[3,4],[5,6]])

# Create another tensor of (3,2)
Y = tf.constant([[7,8],[9,10],[11,12]])

X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [40]:
# Try to Matrix multiply tensors of same shape
X @ Y

InvalidArgumentError: ignored

In [41]:
#Try to multiply tensors of same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [43]:
# Let us change the shape of y
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [44]:
# Try to multiply X by reshaped Y
X @tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [45]:
X.shape , tf.reshape(Y,shape = (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [46]:
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [49]:
tf.reshape(X, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [48]:
# Let us change the shape of X
tf.matmul(Y, tf.reshape(X, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [51]:
# Can do the same with transpose
X , tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [53]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose (X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

##The dot product

Matrix multiplication is also referred as the dot product.

You can perform matrix multiplication using:
  tf.matmul()
  tf.tensordot()

In [55]:
#Perform the dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [56]:
# Perform matrix multiplication between X and y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [59]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [65]:
# Check the values of Y, reshape Y and transposed Y

print("Normal Y:")
print(Y, "\n") # "\n is for newline"

print("Reshaped Y:")
print(tf.reshape(Y, (2,3)), "\n")

print("Transposed Y:")
print(tf.transpose(Y), "\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



### Generally, when perfoming matrix multiplication on two different tensors of different shapes, we would transpose one or the other tensor rather than reshaping to satisfy matrix multiplication rules.

## Change the datatype of a tensor

In [71]:
# Create a new tensor with default datatype (float 32)
B = tf.constant([1.7,7.4])
B , B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [76]:
C = tf.constant([7,10])
C , C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [73]:
# Change from float 32 to float 16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [75]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [78]:
E_float = tf.cast(E, dtype = tf.float16)
E_float

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to smaller amount of values.

In [79]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [80]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Let us go through the following forms of aggregation 

* Minimum
* Maximum
* Mean
* Sum

In [83]:
# Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([50, 86, 13, 32, 47, 87, 86, 12, 62, 37,  1, 19, 78, 36, 98, 31, 58,
       80, 62, 89, 30,  4, 71, 97, 51, 16, 98, 94, 86, 24, 56, 24, 42, 17,
       79, 66, 36, 36, 34, 28,  1,  1, 23, 26, 48, 60, 61, 10, 40, 56])>

In [84]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [85]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [86]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [87]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [88]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2379>

In [109]:
# Find the Standard Deviation
# The input tensor must be in real or complex type. So, we will just convert our data to float

E = tf.cast(E, dtype=tf.float16)
print("The Standard Deviation of E is :", tf.math.reduce_std(E))  # Standard Deviation

# To convert Standard deviation into variance, we will have to square the value.
print("The Variance of E is :", tf.math.square(tf.math.reduce_std(E)))  # Variance

print("The Variance of E is :", tf.math.reduce_variance(E)) # Variance, the standard way!

# Importing Tensorflow probability module
import tensorflow_probability as tfp

print(
    "The Variance of E using Tensorflow probability is :", tfp.stats.variance(E)
)  # Variance


The Standard Deviation of E is : tf.Tensor(28.8, shape=(), dtype=float16)
The Variance of E is : tf.Tensor(829.5, shape=(), dtype=float16)
The Variance of E is : tf.Tensor(829.5, shape=(), dtype=float16)
The Variance of E using Tensorflow probability is : tf.Tensor(829.5, shape=(), dtype=float16)


## Find the positional minimum and maximum

In [111]:
# Create a new tensor for finding positional minimum and maximum.
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [116]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [117]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [118]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [121]:
#Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [123]:
# Find the min value of F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [122]:
#Index on our least value position
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Squeezing a tensor (REMOVING ALL SINGLE DIMENSIONS)

In [127]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [128]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [129]:
#Removes dimensions of size 1 from the shape of a tensor
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One-hot encoding tensors

In [130]:
# Create a list of indices
some_list = [0,1,2,3]  #could be red,green,blue,purple

#One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [132]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value = "I love Deep learning", off_value ="I love Tensorflow")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love Deep learning', b'I love Tensorflow',
        b'I love Tensorflow', b'I love Tensorflow'],
       [b'I love Tensorflow', b'I love Deep learning',
        b'I love Tensorflow', b'I love Tensorflow'],
       [b'I love Tensorflow', b'I love Tensorflow',
        b'I love Deep learning', b'I love Tensorflow'],
       [b'I love Tensorflow', b'I love Tensorflow', b'I love Tensorflow',
        b'I love Deep learning']], dtype=object)>

## More Math Functions 

In [133]:
## Squaring, log, square root

In [134]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [135]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [143]:
# Square root
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [149]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [151]:
#Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [152]:
#Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [153]:
J = tf.constant([3.])
J.numpy(), type(J.numpy())

(array([3.], dtype=float32), numpy.ndarray)

In [161]:
# The default types of each are slighly different
numpy_J = tf.constant(np.array([[10.0, 11], [12, 13]]))
tensor_J = tf.constant([[10.0, 11], [12, 13]])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [165]:
#Physical devices available
tf.config.list_physical_devices() #We are running on a CPU right now.

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [1]:
#Checking access to GPU
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Sun Jul 11 17:58:53 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Note : If you have access to a CUDA enabled GPU, TensorFlow would automatically use it whenever possible.